name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION_NUMBER=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_number=$VERSION_NUMBER" >> $GITHUB_OUTPUT
          echo "Releasing version: $VERSION"

      - name: Build binaries
        run: |
          VERSION=${{ steps.version.outputs.version_number }}

          # Linux x86_64
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.version=$VERSION" -o irc-client-Linux-x86_64

          # Linux aarch64
          GOOS=linux GOARCH=arm64 go build -ldflags "-s -w -X main.version=$VERSION" -o irc-client-Linux-aarch64

          # Darwin x86_64
          GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w -X main.version=$VERSION" -o irc-client-Darwin-x86_64

          # Darwin arm64
          GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w -X main.version=$VERSION" -o irc-client-Darwin-arm64

          # Create checksums
          sha256sum irc-client-* > checksums.txt

      - name: Generate release notes
        id: notes
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$LATEST_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse)
          else
            COMMITS=$(git log ${LATEST_TAG}..HEAD --pretty=format:"- %s (%h)" --reverse)
          fi

          cat > release_notes.md << EOF
          ## Changes

          $COMMITS

          ## Installation

          Download the appropriate binary for your platform:

          \`\`\`sh
          # Detect your platform
          OS=\$(uname -s)
          ARCH=\$(uname -m)

          # Download
          wget https://github.com/\${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/irc-client-\${OS}-\${ARCH}

          # Make executable
          chmod +x irc-client-\${OS}-\${ARCH}
          mv irc-client-\${OS}-\${ARCH} irc-client

          # Run
          ./irc-client irc.libera.chat/6697 yournickname
          \`\`\`

          ### Available binaries:
          - \`irc-client-Linux-x86_64\` - Linux AMD64
          - \`irc-client-Linux-aarch64\` - Linux ARM64
          - \`irc-client-Darwin-x86_64\` - macOS Intel
          - \`irc-client-Darwin-arm64\` - macOS Apple Silicon
          EOF

          echo "Release notes generated"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          body_path: release_notes.md
          files: |
            irc-client-Linux-x86_64
            irc-client-Linux-aarch64
            irc-client-Darwin-x86_64
            irc-client-Darwin-arm64
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
